before_script:
  - apt-get update -qq && apt-get install -y -qq build-essential python3 python3-pip

build:
  script:
    - pip3 install virtualenv
    - bash ./prepare_virtual_environment.sh

make:
  script:
    - bash ./make.sh

